### ISSUE TITLE
运行run.py报错

### ISSUE THREAD

**Issue by mxiwiwn** [Hank0626/CALF#2]
请问在交叉注意力机制的地方出现错误，应该怎么解决？
![微信图片_20240622101704](https://github.com/Hank0626/CALF/assets/146096507/9c74a87b-212b-4d74-9f82-ca967a63c597)

**Comment by Hank0626** [comment]
检查下`d_model`是不是设置成512了，需要设置成768与GPT2的word token embeddings的hidden dimension一致

**Comment by mxiwiwn** [comment]
> 检查下`d_model`是不是设置成512了，需要设置成768与GPT2的word token embeddings的hidden dimension一
谢谢，已解决
