### ISSUE TITLE
zero-shot怎么实现

### ISSUE THREAD

**Issue by mxiwiwn** [Hank0626/CALF#3]
我看scripts/zero-shot-forecasting文件夹中的ETTh1.sh最后有设置zero_shot和target_data参数的，但是run.py文件里面那没有，这两个参数怎么传的呢？
![微信图片_20240623155122](https://github.com/Hank0626/CALF/assets/146096507/9811a728-c66d-49f0-810c-25362669a695)

**Comment by Hank0626** [comment]
你好，过几天会修复

**Comment by mxiwiwn** [comment]
> 你好，过几天会修复

哦哦好滴

**Comment by Hank0626** [comment]
@mxiwiwn 已解决，请参考最新的代码

**Comment by mxiwiwn** [comment]
> @mxiwiwn 已解决，请参考最新的代码

好的，谢谢！
