### ISSUE TITLE
LoRA

### ISSUE THREAD

**Issue by flying-cmd** [Hank0626/CALF#5]
文中提到使用LoRA微调LLM，但models/CALF.py中把self.gpt2 = get_peft_model(self.gpt2, peft_config)注释掉了，是在其他地方用了LoRA吗？

![image](https://github.com/user-attachments/assets/02c5e520-0ee4-4fa5-8a7e-9e877813f549)

**Comment by Hank0626** [comment]
是之前跑消融忘取消注释了；已经更新。
